import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import extractedColors from "@/data/sample-extracted-palette.json";
import { ALGORITHMS, PREVIEW_SIZE, PREVIEW_SOURCE } from "@/lib/algorithms";
import { readGifInfo } from "@/lib/editor/gif/decode";
import { PALETTE_PRESETS } from "@/lib/palettes";
import {
  ANIMATED_DITHER,
  ANIMATED_SAMPLE,
  EXTRACTED_PREVIEW_COLORS,
  HERO_ALGORITHMS,
  HERO_ORIGINAL,
  HERO_PALETTES,
  heroSize,
  heroVariant,
  PALETTE_PREVIEW_SIZE,
  palettePreview,
  PIXEL_ART_PREVIEW,
  SAMPLE_IMAGE,
} from "@/lib/samples";

// Generated by scripts/generate-previews.mjs; these tests catch a missing
// or stale run after adding a palette or algorithm.
const publicFile = (path: string) =>
  join(process.cwd(), "public", path.slice(1));

function pngSize(path: string) {
  const file = readFileSync(publicFile(path));
  return { width: file.readUInt32BE(16), height: file.readUInt32BE(20) };
}

describe("generated assets", () => {
  it("has the sample image at its declared size", () => {
    expect(pngSize(SAMPLE_IMAGE.src)).toEqual({
      width: SAMPLE_IMAGE.width,
      height: SAMPLE_IMAGE.height,
    });
  });

  it("has the animated sample at its declared size and length", () => {
    const file = readFileSync(publicFile(ANIMATED_SAMPLE.src));
    expect(readGifInfo(new Uint8Array(file))).toEqual({
      width: ANIMATED_SAMPLE.width,
      height: ANIMATED_SAMPLE.height,
      frames: ANIMATED_SAMPLE.frames,
    });
  });

  it.each([...PALETTE_PRESETS.map((p) => p.id), "extracted"])(
    "has a %s palette preview",
    (id) => {
      expect(pngSize(palettePreview(id))).toEqual(PALETTE_PREVIEW_SIZE);
    },
  );

  it("has the pixel art preview at its native size", () => {
    expect(pngSize(PIXEL_ART_PREVIEW.src)).toEqual({
      width: PIXEL_ART_PREVIEW.width,
      height: PIXEL_ART_PREVIEW.height,
    });
  });

  it("records the colors of the 'From image' preview", () => {
    expect(extractedColors).toHaveLength(EXTRACTED_PREVIEW_COLORS);
    for (const color of extractedColors)
      expect(color).toMatch(/^#[0-9a-f]{6}$/);
  });

  it("has the algorithm specimen at its declared size", () => {
    expect(pngSize(PREVIEW_SOURCE)).toEqual({
      width: PREVIEW_SIZE,
      height: PREVIEW_SIZE,
    });
  });

  it.each(ALGORITHMS.map((a) => [a.slug, a.preview]))(
    "has a %s algorithm preview",
    (_, preview) => {
      expect(existsSync(publicFile(preview))).toBe(true);
      expect(pngSize(preview)).toEqual({
        width: PREVIEW_SIZE,
        height: PREVIEW_SIZE,
      });
    },
  );

  it.each(
    HERO_ALGORITHMS.flatMap((algorithm) =>
      HERO_PALETTES.map((palette) => [algorithm, palette] as const),
    ),
  )("has the %s × %s hero variant", (algorithm, palette) => {
    expect(pngSize(heroVariant(algorithm, palette))).toEqual(
      heroSize(algorithm),
    );
  });

  it("has the hero original at its declared size", () => {
    expect(pngSize(HERO_ORIGINAL.src)).toEqual({
      width: HERO_ORIGINAL.width,
      height: HERO_ORIGINAL.height,
    });
  });

  it("has the dithered animated sample and its still", () => {
    const size = {
      width: ANIMATED_DITHER.width,
      height: ANIMATED_DITHER.height,
    };
    const file = readFileSync(publicFile(ANIMATED_DITHER.src));
    expect(readGifInfo(new Uint8Array(file))).toEqual({
      ...size,
      frames: ANIMATED_SAMPLE.frames,
    });
    expect(pngSize(ANIMATED_DITHER.still)).toEqual(size);
  });
});
